### ISSUE TITLE
Failed to compile with Next.js

### ISSUE THREAD

**Issue by EvaFro** [tryfoobar/commandbar-launcher#4]
I wanted to use this helper for our product, but we use next.js and when I try to add the `<Launcher />` I get this error due to the way the index file is handling the CSS import. 

https://nextjs.org/docs/messages/css-npm

![Screen Shot 2022-01-18 at 3 36 51 PM](https://user-images.githubusercontent.com/24962853/150035946-7fe2a281-67b1-45a4-b344-6a872a169315.png)
![Screen Shot 2022-01-18 at 3 41 11 PM](https://user-images.githubusercontent.com/24962853/150036439-dd1bce75-e174-4f9a-a849-7b3963747974.png)

**Comment by vayyala** [comment]
Fixed in `v1.1.8`! https://github.com/tryfoobar/commandbar-launcher/releases/tag/1.1.8
